server:
  port: 8080

camel:
  component:
    servlet:
      mapping:
        context-path: /services/*
  spring-rabbitmq:
     auto-declare: true

metrics: 0 */1 * * * * # seconds minutes hours days months years
#expose actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - prometheus


mfoumgroup:
    camel:
      hello:
        enabled: false
      file:
        enabled: false
      rest-metrics:
        enabled: false
      wiretap:
        enabled: false
      seda:
        enabled: false
      rest:
        enabled: true
      rest-dsl:
        enabled: true
      weather:
        enabled: true
