server:
  port: 8080

camel:
  component:
    servlet:
      mapping:
        context-path: /services/*
  spring-rabbitmq:
     auto-declare: true


mfoumgroup:
    camel:
      hello:
        enabled: false
      file:
        enabled: false
      rest-metrics:
        enabled: false
      wiretap:
        enabled: false
      seda:
        enabled: false
      rest:
        enabled: true
      rest-dsl:
        enabled: true
      weather:
        enabled: true
